name: Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo service docker start

      - name: Build Docker Image
        run: |
          docker build -t my-docker-image .

      - name: Run Docker Container
        run: |
          docker run -d --name my-container -p 8080:80 my-docker-image
